### ISSUE TITLE
Why isn't this package registered?

### ISSUE THREAD

**Issue by mohdibntarek** [nsmith5/PyGen#2]
I wonder why don't you register this package, seems like a useful package especially for recursive generators.

**Comment by nsmith5** [comment]
I'm glad you find the package useful. The reception about the name seemed a bit mixed when I first announced it so I didn't want to fight it too much trying to merge into METADATA honestly. Also, I'm writing my thesis right now. My thesis will be submitted in 2 weeks then I'd love to give this package some more love and look into registration.

**Comment by mohdibntarek** [comment]
Cool, good luck with your thesis! Just please pre-announce if you are planning to change the package's name, because I am using it in my own packages, thanks!

**Comment by nsmith5** [comment]
Yes, of course, will do!

________________________________

**Comment by nsmith5** [comment]
Hey @mohamed82008 take a look at [ResumableFunctions](https://github.com/BenLauwens/ResumableFunctions.jl). This package is prerelease, but its a better implementation of this concept and it likely headed towards registration. I'll be putting my efforts behind this project rather than working on `PyGen`

**Comment by mohdibntarek** [comment]
Cool! My main use case for which PyGen was really convenient is for recursive generators, I will need to check if ResumableFunctions pulls the same trick or not. Thanks for the recommendation.

**Comment by mohdibntarek** [comment]
Just wanted to let you know I still prefer PyGen :) [comparison](https://discourse.julialang.org/t/ann-resumablefunctions/5711/4)
