### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by femtotrader** [nsmith5/PyGen#3]
Hello,

Most Julia packages are using repositories ending by `.jl`
https://github.com/JuliaStats/DataFrames.jl
https://github.com/JuliaStats/TimeSeries.jl
...

It should be the same for this one.

Kind regards

PS : PyGen is also a strange name because it could lead to confusion that it's using Python.
But this project is not a wrapper for a Python library (like https://github.com/JuliaPy/PyCall.jl https://github.com/JuliaPy/PyPlot.jl ... )
see https://discourse.julialang.org/t/pygen-python-style-generators/3451/6

**Comment by nsmith5** [comment]
See [ResumableFunctions](https://github.com/BenLauwens/ResumableFunctions.jl)
